### ISSUE TITLE
[Question] How to use env variables?

### ISSUE THREAD

**Issue by subzero911** [felixblaschke/shelf_plus#19]
![image](https://user-images.githubusercontent.com/12999702/177220547-b4a191f5-f8a1-4995-bef4-2ec1301e9387.png)
You said that configuration can be set via env variables but didn't explain how exactly.
For example, I want to change SHELF_ADDRESS to 0.0.0.0 for production server. What should I do for it?
How can I pass this variable to the running server?

**Comment by felixblaschke** [comment]
The concept of environment variables is a basic concept of any OS and is covered in computer science educations.

https://wiki.archlinux.org/title/environment_variables
