### ISSUE TITLE
Getting connection information from routers

### ISSUE THREAD

**Issue by chrisnorman7** [felixblaschke/shelf_plus#20]
Hi,
I would like to get connection information from a particular shelf router, and I'm struggling. I've done a fair amount of googling, and I'm starting to think it's not possible with this package.

Can you confirm please?

Thanks in advance.

**Comment by felixblaschke** [comment]
Follow up. I found this out: https://github.com/dart-lang/shelf/blob/master/pkgs/shelf/lib/shelf_io.dart#L178

You will find a connection info within the context of a shelf request: e.g. `request.context['shelf.io.connection_info']`

**Comment by chrisnorman7** [comment]
@felixblaschke 
Thank you so much for the info, that worked perfectly.
