### ISSUE TITLE
remove server start up message

### ISSUE THREAD

**Issue by HosamHasanRamadan** [felixblaschke/shelf_plus#21]
Thank you for this amazing package.
I am using this package in console application .
Is it possible to remove server start up message or make it configurable ?

https://github.com/felixblaschke/shelf_plus/blob/db8203c35f52f6d554664dc7a8c91958839bc487/lib/src/shelf_run.dart#L76

**Comment by felixblaschke** [comment]
Hi! This sounds sensible :-)

Feel free to submit a suggestion PR

**Comment by felixblaschke** [comment]
Resolved with version `1.4.1`
