### ISSUE TITLE
Wildcard or "route not found" handling?

### ISSUE THREAD

**Issue by inselberg** [felixblaschke/shelf_plus#24]
Hi,

is there a way to handle wildcard requests? Or catch unknown routes?

greetngs.

**Comment by felixblaschke** [comment]
Hi, shelf_plus uses the "official" router engine from shelf_router. From what I've seen, it allows you to have wildcard also with regex matching (last example in link). Maybe this helps you:

https://pub.dev/documentation/shelf_router/latest/shelf_router/Router-class.html

**Comment by felixblaschke** [comment]
You can also add a default not found handler to `Router()` constructor: https://pub.dev/documentation/shelf_router/latest/shelf_router/Router/Router.html

And then calling the `.plus` extension.
