### ISSUE TITLE
Equality for WebSocketUsers

### ISSUE THREAD

**Issue by victor7w7r** [felixblaschke/shelf_plus#26]
Hello, I have an inconvenience about getting information for websocket clients, when connecting, it is added to a ws list

```dart
final usersSessions = <WebSocketSession>[];
...
onOpen: (ws) {
   usersSessions.add(ws);
};
```

But, when i want to remove a specific user from the list, it says that all `ws` are the same

```dart
...
onClose: (ws) {
  for(var user in usersSessions) {
     print(user == ws); //ALL IS TRUE
  }
   usersSessions.remove(ws);
};
```

I need to verify and know which user is disconnected to do specific actions to the information of each one.

Is there any way to differentiate one user from another within the websocket? thanks for the patience and excellent work 😄

**Comment by felixblaschke** [comment]
Hi, the official example is make use of equality: https://github.com/felixblaschke/shelf_plus/blob/main/example/example_websocket_chat/bin/example_websocket_chat.dart#L24

If it's still not working for you, please provide a repository with a minimal example.

**Comment by victor7w7r** [comment]
> Hi, the official example is make use of equality: https://github.com/felixblaschke/shelf_plus/blob/main/example/example_websocket_chat/bin/example_websocket_chat.dart#L24
> 
> If it's still not working for you, please provide a repository with a minimal example.

https://github.com/victor7w7r/WebSocketUsers/blob/main/bin/main.dart

No, still not working, here is an example of mine with all the doubts, if it is possible that you help me, much more on how I verify which user is disconnected. thank you so much 😢

**Comment by felixblaschke** [comment]
Your problem is, that you have a single `WebSocketSession` instance shared among all users:
```dart
app.get('/socket', () => socket); // every use gets `socket`
```

What you need to do is to create a new instance each endpoint call:
```dart
app.get('/socket', () => WebSocketSession(...);
```
If you want to put the code for that somewhere else use a factory-like method for that, e.g.
```dart
app.get('/socket', () => createNewWebSocketSession());
```

**Comment by victor7w7r** [comment]
Thank you so much, it works! 😄

**Comment by victor7w7r** [comment]
Thank you so much, it works! 😄 sorry for the inconvenience
