### ISSUE TITLE
onStartFailed CallBack!

### ISSUE THREAD

**Issue by omegaui** [felixblaschke/shelf_plus#27]
@felixblaschke 
```dart

void main(List<String> args) {
  try {
    initConfig(args.first);
    shelfRun(init, defaultBindAddress: host,
        defaultBindPort: port,
        onStarted: (address, port) =>
            print('[STARTED] Listening at http://$address:$port'));
  }
  on SocketException catch(e){
    print("[FAILED] Cannot start the server!");
    print(e);
  }
}
```
Hi!
I am writing a chat program,
I come across this problem that
There is a `onStarted` callBack but I can't find a way to know implicitly if the server has failed to start!
Not even `try-catch` block can handle it cause it seems that server launch is a async operation.

Likewise `onStarted`, there should be a `onStartFailed` callback.

**Comment by felixblaschke** [comment]
Hi there,

Thanks for opening the issue and reporting the missing function in our open source project. We appreciate your feedback and contribution.

We encourage you to take on the challenge and implement the missing function yourself. We believe in your abilities and it would be great if you could submit your solution in a pull request.

Looking forward to seeing your implementation and having you as part of our community.
