### ISSUE TITLE
shelf_plus 1.8.0 was not compatible with flutter 3.19.1, shows error after upgrade flutter from 3.16.9 to 3.19.1

### ISSUE THREAD

**Issue by leefordjudes** [felixblaschke/shelf_plus#34]
Shows error like the below, after upgrading flutter 3.19.1 from 3.16.9
<code>
flutter pub upgrade
Resolving dependencies...
Note: vm_service is pinned to version 13.0.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because hotreloader >=3.0.3 <3.0.5 depends on vm_service >=6.0.1 <9.0.0 and hotreloader >=3.0.5 <3.0.6 depends on vm_service >=6.0.1 <10.0.0, hotreloader >=3.0.3 <3.0.6 requires vm_service >=6.0.1 <10.0.0.
And because hotreloader >=3.0.6 <4.1.0 depends on vm_service >=6.0.1 <12.0.0 and every version of flutter_test from sdk depends on vm_service 13.0.0, flutter_test from sdk is incompatible with hotreloader >=3.0.3 <4.1.0.
And because shelf_plus >=1.5.1 depends on shelf_hotreload ^1.4.0 which depends on hotreloader ^3.0.4, flutter_test from sdk is incompatible with shelf_plus >=1.5.1.
So, because pos_server depends on both shelf_plus ^1.8.0 and flutter_test from sdk, version solving failed.
exit code 1
</code>

Kindly resolve.

**Comment by felixblaschke** [comment]
hey 😄 ...thanks for raising that. I upgraded the depencies. Can you please retest if it works now?

**Comment by leefordjudes** [comment]
yes, it works with shelf 1.9, and compatible with flutter 3.19.1
thank you for your immediate response.

**Comment by felixblaschke** [comment]
Nice. Thank you for verifying 👍
