### ISSUE TITLE
`shelfRun` uses `writeln` which is not thread-safe

### ISSUE THREAD

**Issue by 0rzech** [felixblaschke/shelf_plus#37]
79bc7c6a05474f559998635989a81315ddd929f6 replaced thread-safe `print` with non-thread-safe `writeln` (see https://github.com/dart-lang/sdk/issues/55345) in `shelfRun`, which results in garbled startup logs when multiple isolates are spawned at once.

**Comment by felixblaschke** [comment]
Thanks for fixing. I release it with 1.9.2
