### ISSUE TITLE
Error: Unhandled Exception: Unsupported operation: Isolate.packageConfig

### ISSUE THREAD

**Issue by NiuBee-Newbie** [felixblaschke/shelf_plus#39]
From the source code below, it print "before theShelf.shelfRun" and "after theShelf.shelfRun" but didn't print anything inside theShelf.Handler init().

Note: compiled on windows using this command: flutter run -d windows

Source code:
```
  import 'package:shelf_plus/shelf_plus.dart' as theShelf;

  print("before theShelf.shelfRun");
  theShelf.shelfRun(init, defaultBindPort: 8080, defaultShared: false);
  print("after theShelf.shelfRun");

  theShelf.Handler init() {
    print("[1]");
    var app = theShelf.Router().plus;
    print("[2]");
    app.get('/', (theShelf.Request request) {
      print("[3]");
      File('thesis.pdf'); //-> not even here, so doesn't matter if the file exist at this moment
    });
    print("[4]");
    return app.call;
  }
```

Detailed error:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Isolate.packageConfig
#0      Isolate.packageConfigSync (dart:isolate-patch/isolate_patch.dart:326:7)
#1      Isolate.packageConfig (dart:isolate-patch/isolate_patch.dart:319:25)
#2      _getPackagesFile (package:hotreloader/src/util/pub.dart:13:39)
#3      packagesFile (package:hotreloader/src/util/pub.dart:17:38)
#4      packagesFile (package:hotreloader/src/util/pub.dart)
#5      HotReloader._registerWatchers (package:hotreloader/hotreloader.dart:146:32)
#6      HotReloader.create (package:hotreloader/hotreloader.dart:110:22)
<asynchronous suspension>
#7      withHotreload (package:shelf_hotreload/src/with_hotreload.dart:87:5)
<asynchronous suspension>

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.8.3)
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2023.2)
[✓] VS Code, 64-bit edition (version 1.87.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

EDIT:
if I run it on android device connected to the windows laptop (command: flutter run --release), the error message is:
E/flutter (25473): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Error: [pubspec.yaml] file not found in current directory.
E/flutter (25473): For hot code reloading to function properly, Dart needs to be run from the root of your project.
E/flutter (25473): #0      HotReloader.create (package:hotreloader/hotreloader.dart:96)
E/flutter (25473): #1      withHotreload (package:shelf_hotreload/src/with_hotreload.dart:87)
E/flutter (25473): #2      shelfRun (package:shelf_plus/src/shelf_run.dart:54)
E/flutter (25473): #3      _MyHomePageState.startServer (package:my_app_name/main.dart:293)
E/flutter (25473): <asynchronous suspension>
E/flutter (25473): #4      _MyHomePageState.androidWebview.<anonymous closure> (package:my_app_name/main.dart:457)
E/flutter (25473): <asynchronous suspension>

**Comment by felixblaschke** [comment]
Hi @NiuBee-Newbie 

It appears that the problem is caused by using the shelf_plus library in conjunction with flutter run. This library is intended to be run with **dart run** and not **flutter run**. 

The error occurs because Isolate.packageConfig is an unsupported operation when executed within the Flutter environment caused by the hotreloader.

Please try running your code with dart run instead of flutter run. This should resolve the issue, as dart run is more compatible with libraries like shelf that are designed for pure Dart applications.

**Comment by NiuBee-Newbie** [comment]
Hi @felixblaschke 

Thanks for the very quick reply. I think I need to use flutter run command, because in the end I will build the installer / bundle using flutter command. So, I decide to build a simple web server using dart.io's HttpServer.

Thanks a lot for your help!
