### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by JannieT** [felixblaschke/shelf_plus#4]
Thanks so much for this package! Very excited.  

For larger projects where we use controllers as route handlers it will be very useful to have a centralized exception handler so we can throw meaningful Http exceptions from further down the stack and have those translated into shelf responses to keep the API clean. The [shelf_exception_handler](https://pub.dev/packages/shelf_exception_handler) package does this very elegantly, but before I try to help get that package up to date, would you consider a PR for such a feature in shelf_plus or maybe you are already working on something similar or better to handle the very common case where, say 

```dart
app.get('/user/<id>', userController.get);
```

will return a well-formed 404 when the id is not in the database. It feels like this is a very central element and should best be integrated in shelf_plus.

**Comment by felixblaschke** [comment]
I am currently not working on such a feature. I also wasn't aware that someone uses this.

The package you mentioned implements this exception handling via middleware. If you get this package running you can use it along with shelf plus router, without any modifications.

How would the ideal webserver code look like? Where do you implemented the exception handler?

**Comment by JannieT** [comment]
Even the simplest of apps needs to handle exceptions. Without a centralized exception handler the routes list can never be neat and readable. This means that every shelf plus user who don't want a messy routes file with all the app code in one file, will have to discover the shelf_exception_handler package as a solution to this problem and register it in the app middleware or they might give it one look and decide shelf plus is only for very small projects where the app logic can't elegantly be broken into smaller modules.

The ideal webserver would come with a central http exception handler baked in and implemented under the hood.

**Comment by JannieT** [comment]
Thanks for the decision, Felix. Looking forward to see how Shelf Plus develops.
