### ISSUE TITLE
Embedded usage in a Flutter app

### ISSUE THREAD

**Issue by Gobbo89** [felixblaschke/shelf_plus#40]
Hello,
according to [pub.dev](https://pub.dev/packages/shelf_plus) shelf_plus usage is supported in Flutter SDK. At least this was my assumption.

However, when launching my test app with `flutter run -d emulator-1`, I receive the following error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Error: [pubspec.yaml] file not found in current directory.
(...)
```
Which is the same error mentioned in #39.
^ There, @felixblaschke has already written that:
> This library is intended to be run with dart run and not flutter run.  

I am a bit confused now: is **shelf_plus** a viable solution if I want to embed an HTTP server in a Flutter application?

If needed, here below is the code that I am using to reproduce, plus my flutter doctor:
<details> 
  <summary>Code</summary>

```dart
import 'package:shelf_plus/shelf_plus.dart';

void main() {
  print('Testing shelf_plus');
  shelfRun(init);
}

Handler init() {
  var app = Router().plus;
  app.get('/text', () => 'a text');
  return app.call;
}

```
</details>
<details> 
  <summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Versione 10.0.22631.4037], locale it-IT)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.6)
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```
</details>

Thank you

**Comment by Gobbo89** [comment]
Hi @felixblaschke, thank you for your fast reply!

> No, shelf_plus is not meant to run in Flutter.

The flutter SDK tag on pub.dev confused me then. Is it intended / am I missing something?

> You need to look for another approach to embed an HTTP server.

Before trying shelf_plus I was using shelf, shelf_router, shelf_web_socket and so on.
I had no issue embedding a decent HTTP server in a flutter app with that approach.
I wanted to try shelf_plus to leverage its abstraction layer and get a DX QOL boost.

That said, I've tried shelf_plus with `dart run` and it's a great package!

**Comment by felixblaschke** [comment]
Maybe there is some kind of scan that looks for dependencies that speak against using it in flutter, eg dart:io or dart:mirrors

**Comment by Gobbo89** [comment]
Maybe. Closing the issue now, thank you.
