### ISSUE TITLE
Feature request: "Request updater" local middleware

### ISSUE THREAD

**Issue by davidmartos96** [felixblaschke/shelf_plus#42]
Hello,
I was interested in writing a middleware that would throw a timeout exception and appropriate response using Future.timeout(...). The problem is that I would also like to be able to override the default timeout for particular routes using `request.change(context: {"timeout": Duration()})` in a local to the route middleware.

What happens now is that this local middleware will run after the "global" middleware that setups the default timeout handling, so I cannot use the request context to configure the appropriate timeout. 

I propose adding a separate parameter to the routes to provide a middleware that will run first in the list. Maybe even limit the API to be `FutureOr<Request> RequestUpdater(Request)`. I'm not sure if there are valid use cases for a full middleware to run before the rest.

**Comment by felixblaschke** [comment]
This sounds you are running in technical limitation of shelf router itself. Remember shelf_plus is just syntax sugar on top of it.

Also this is very specific to handling timeouts.

To me it reads as if you only face the issue when the local timeout is higher than the global one. For that case I suggest adding specific exception in the global one. I find it more expected that the global timeout would contain all limits and sub-routes can not override them (only be more strict).

What do you think?

**Comment by davidmartos96** [comment]
@felixblaschke Your solution would work, but on our use case it fits much better the other way around. A most common timeout for all routes, and have a greater one only on specific routes.

I agree on shelf_plus being an extension. Wouldn't the implementation be adding the middleware to the beginning of the list instead of to the end? Or am I missing some other behavior?

**Comment by felixblaschke** [comment]
I think you can't just change how shelf works. It uses a one pass:

```
Adapter --> List<Middleware>--> Handler
```
A router is just a fancy way to tell which handler should be picked.

What I understood you are proposing is a dual pass architecture where you first do all the routing to retrieve "meta data", where e.g. the handler is asked to provide a specific "timeout limit meta data", so in the second pass the global middleware can timeout it accordingly.

To me this looks too much like working around shelf's architecture. Or am I missing something?

**Comment by davidmartos96** [comment]
I've found an alternative way to handle timeouts.
Instead of wrapping the innerHandler with a .timeout, keep a Timer in the context, and let an individual route cancel a previous Timer, if there is one, or start a Timer that will throw when it ends.
That way, only the most inner timeout middleware will be considered.
