### ISSUE TITLE
Export shelf_io

### ISSUE THREAD

**Issue by hacker1024** [felixblaschke/shelf_plus#5]
This package exports shelf and shelf_router, but it does not export shelf_io. This means that to launch the server, `shelf` must be added to the pubspec.

**Comment by felixblaschke** [comment]
You can always use it along with shelf_io and add those dependency to your project.
I intended to use it with shelf run: https://github.com/felixblaschke/shelf_plus#shelf-run

**Comment by hacker1024** [comment]
Fair enough. I don't think shelf run fits my use case - I'm building a package that uses Shelf internally. Developers may not call `start` immediately after launch, so I don't think shelf run can be used.

**Comment by felixblaschke** [comment]
I totally agree that larger application will do own initialization. Those teams get how to add shelf_io dependency :)

Shelf run is more a beginner tool that comes with hot-reload.
